[package]
name = "greet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

# TODO: Use https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
