[package]
name = "mei"
version = "0.3.1"
edition = { workspace = true }
description = "Cargo build subsystem"
license = "Apache-2.0"

[dependencies]
semver = "1"

[dependencies.toml]
version = "0.21"
package = "toml_edit"
default-features = false
features = ["parse"]
