[package]
name = "mei"
version = "0.3.0"
edition = "2021"
description = "Cargo build subsystem"
license = "Apache-2.0"

[dependencies.toml]
version = "0.21"
package = "toml_edit"
default-features = false
features = ["parse"]
